"""Write .streamlit/config.toml from the design tokens.

    python scripts/build_theme.py           # write the file
    python scripts/build_theme.py --check   # fail if it is out of date

The token set in src/septic/report/assets.py is the source of truth for every
colour on both surfaces. This turns the subset the Streamlit shell needs into the
config file Streamlit reads before any of our code runs, so the shell and the
report are the same palette rather than two palettes that happen to agree.

There is no business logic here. tests/test_theme.py runs the same comparison, so
a token changed without regenerating the file fails the suite rather than showing
up on a projector.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from septic.report.assets import STREAMLIT_THEME, TOKENS  # noqa: E402

CONFIG = ROOT / ".streamlit" / "config.toml"


def render() -> str:
    """The config file, as text, from the tokens."""
    colour = TOKENS["colour"]
    width = max(len(option) for option, _ in STREAMLIT_THEME)
    lines = [
        "# Generated by scripts/build_theme.py from the design tokens in",
        "# src/septic/report/assets.py, which is the source of truth for every",
        "# colour on both surfaces. Do not edit this file by hand: change the",
        "# tokens, run the script, and commit the result. tests/test_theme.py",
        "# fails if this file and the tokens disagree.",
        "#",
        "# Why it exists. Without it Streamlit builds its chrome from whatever the",
        "# operating system reports, so on a machine set to dark mode the app drew",
        "# a near black shell and painted this light palette onto it. Secondary",
        "# body copy measured about 1.7 to 1 against that background and the three",
        "# verdict names could not be read at all. A light theme is the decision",
        "# here, not a default, so it is pinned in both slots below and the",
        "# rendering does not change with the machine it is presented from.",
        "",
        "[theme]",
        '# Streamlit\'s light theme is the base, then every value it reads is',
        "# replaced by the token beside it.",
        'base = "light"',
    ]
    for option, token in STREAMLIT_THEME:
        lines.append(f'{option:<{width}} = "{colour[token]}"  # colour.{token}')
    lines.extend([
        "",
        "# The same system font stacks the report and the console use. Set here so",
        "# Streamlit applies them to its own body font, rather than the console",
        "# overriding them in CSS: a selector broad enough to catch Streamlit's",
        "# text also caught its icon font, and every icon then rendered as the",
        "# name of its own ligature, which is what made the upload control read",
        "# uploadUpload.",
        f"font = '{TOKENS['font']['sans']}'",
        f"codeFont = '{TOKENS['font']['mono']}'",
        "",
        "# Pinned to the same light values, so a dark operating system cannot pull",
        "# the shell out from under the palette. Inheriting the visitor's theme is",
        "# what broke this in the first place.",
        "[theme.dark]",
    ])
    for option, token in STREAMLIT_THEME:
        lines.append(f'{option:<{width}} = "{colour[token]}"  # colour.{token}')
    lines.extend([
        "",
        "[browser]",
        "# No usage ping. The console has to render identically on venue wifi that",
        "# has failed, and this is a network call at start up.",
        "gatherUsageStats = false",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the file is out of date")
    args = parser.parse_args()

    wanted = render()
    if args.check:
        found = CONFIG.read_text(encoding="utf-8") if CONFIG.is_file() else ""
        if found != wanted:
            print(f"{CONFIG} is out of date. Run python scripts/build_theme.py")
            return 1
        print(f"{CONFIG} matches the tokens")
        return 0

    CONFIG.parent.mkdir(parents=True, exist_ok=True)
    CONFIG.write_text(wanted, encoding="utf-8")
    print(f"wrote {CONFIG}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
